### ISSUE TITLE
Not receiving "code"

### ISSUE THREAD

**Issue by Pontiac76** [ajikan/ScribeAI#1]
If I ask ScribeAI to show me a certain type of code (Basic example provided), it teases me saying "Here's your code" but shows nothing.

![image](https://user-images.githubusercontent.com/4532020/215357221-a469cf8f-21dc-4aca-9a24-31e442c153b3.png)

**Comment by ajikan** [comment]
Hello, thanks for opening the issue. However, I think this is not an issue with extension but just with openai and how you worded your question. Like most people know, the wording of your questions is very important in determining the quality of the output response you get from openai models. The more descriptive and detailed your question is, the better the response you'll get from openai. This has been true for ChatGPT and this is even more true for text-davinci-003 and code-davinci-002. The results you get from ChatGPT is better compared to text-davinci-003 and code-davinci-002 but currently the official API for ChatGPT is not out yet. I plan to integrate ChatGPT once the official API comes out. The extension uses code-davinci-002 by default since it's free but text-davinci-003 might give you better performance. I would suggest to try rewording your question and provide more detail, you can check out the openai docs on good tips for wording your question. Or you can try switching the model to text-davinci-003 by going to Code -> Preferences -> Settings -> User -> Extensions -> ScribeAI.

**Comment by ajikan** [comment]
In the latest release 1.1.0, I modified the chatbot to provide more detailed response through prompt engineering and additional tuning. I think now it will provide you with better answers. Please try it out and let me know how it goes. Thanks!

**Comment by Pontiac76** [comment]
The problem wasn't what I was asking, but what it answer was, or wasn't.  It clearly says "Here's your code" but doesn't present any code.  That's what I was reporting on.

I'm running this on my laptop which has never seen this plugin before now, and I asked the same question, and this time I did get an answer.  I'll close this one up.
